#!/bin/bash
set -e

find . -type f \
    \( -iname '*.aux' \
    -o -iname '*.o' \
    -o -iname '*.cmi'  \
    -o -iname '*.cmo'  \
    -o -iname '*.cmx'  \
    -o -iname '*.vo'  \
    -o -iname '*.vos'  \
    -o -iname '*.vok'  \
    -o -iname '*.glob'  \
    -o -iname '*.ml'  \
    -o -iname '*.mli'  \
    -o -iname '*/qc_exec'  \
    -o -iname '*.native'  \
    -o -iname '/.Makefile.d' \
    -o -iname '/.CoqMakefile.d' \
    -o -iname '*/CoqMakefile'  \
    -o -iname '/.lia.cache' \
    -o -iname '*.out'  \
    -o -iname '*.conf' \
    -o -iname '*_exec' \) \
    -delete