#!/bin/bash

# Save the test result
result="$(raco test src/spec.rkt)" ;

# Remove the first line of the result
result="$(sed '1d' <<< "$result")"

# Create the javascript code that uses the result
# ```
# const initialInput = `
# ${result}
# `;
# document.getElementById('traceInput').value = initialInput;
# ```
result="const initialInput = \`$result\`;
document.getElementById('traceInput').value = initialInput;"

# Change the contents of the initialInput between `<script id="input"> and </script>` tags in the copy.html file
perl -0777 -i -pe "s|<script id=\"input\">.*?</script>|<script id=\"input\">\n$result\n</script>|gs" copy.html

open copy.html