#!/bin/bash
set -e
############################################################
# Help                                                     #
############################################################
Help()
{
   # Display Help
   echo "This script compiles a given Coq project using _CoqProject file."
   echo
   echo "Syntax: build [-c|i|h]"
   echo "options:"
   echo "c     run 'make clean' before the build."
   echo "i     run 'make install' after the build."
   echo "h     print help."
   echo
}

############################################################
############################################################
# Main program                                             #
############################################################
############################################################

# Get the options
while getopts ":hci" option; do
    case $option in
        h) # display Help
            Help
            exit;;
        c)
            should_clean=True;;
        i)
            should_install=True;;
        \?) # incorrect option
        echo "Error: Invalid option $OPTARG" >&2
        exit;;
   esac
done

coq_makefile -f _CoqProject -o Makefile

if [ "$should_clean" = "True" ]; then
    make clean
fi

make

if [ "$should_install" = "True" ]; then
    make install
fi